### ISSUE TITLE
Hardware specs?

### ISSUE THREAD

**Issue by iplayfast** [GearDownForWhat/BalanceBot#1]
Code is good, but in the last video, you've got a nano as well as a mega.  Does the code specify which process it is for? Also hardware used would be mildly useful :)
Links to relevant pages in a md format page would also be useful. The videos say your projects are on thingiverse so link to this projects thingiverse page would also be good. I wasn't able to find it.

As an idea, from your video description I'm not sure you are doing this, but if you have a pid driving the pid you can get dynamic "dead zones" something to look into.

**Comment by GearDownForWhat** [comment]
Working on getting everything organized, we reduced the number of processors to 1.

What do you mean by dynamic deadzones?

**Comment by iplayfast** [comment]
You mentioned in the video that by giving a deadzone the bot was more stable. You can make the dead zone move around depending on where you want the acceleration. The pid controlling that keeps things from going too crazy faster they you can react, so it's overall more controllable.

**Comment by GearDownForWhat** [comment]
I actually removed the deadband from the program since I started using the Odrive, I think.
