### ISSUE TITLE
Question: how about dirt/gravle roads? 

### ISSUE THREAD

**Issue by jh83** [GearDownForWhat/BalanceBot#2]
This post is a question and not related to any bug.

How well does the current version of the software handle driving on uneven surfaces like gravele/dirt roads? Does it manage the vibrations caused by the gravle and holes and such which might exist outside pavement roads?

**Comment by GearDownForWhat** [comment]
It doesn't do well on low friction surfaces, for example on wet pavement it's very hard to control. 

You could make it a bit more dependable on low friction surfaces by de-tuning the PID loops a bit
